services:
  - type: web
    name: my-backend
    env: python
    region: oregon
    plan: free

    buildCommand: |
      pip install -r backend/requirements.txt

    startCommand: |
      uvicorn backend.main:app --host 0.0.0.0 --port 8000

    envVars:
      - key: PYTHON_VERSION
        value: 3.10

      # Environment variables
      - key: GROQ_API_KEY
        sync: false

      - key: DATABASE_URL
        sync: false
